### ISSUE TITLE
Fails in repo with no tags

### ISSUE THREAD

**Issue by ldoolitt** [yetifrisstlama/kiff#2]
$ kiff *.pro -c HEAD~1
layers: F.Cu B.Cu F.SilkS B.SilkS
fatal: No names found, cannot describe anything.
No git description, can't continue
$ git describe --dirty      
fatal: No names found, cannot describe anything.
$ git log | head
commit 75827f9b4f035845c8be30596e890e0cd2332509
Author: michalgaska [...]

**Comment by michael-betz** [comment]
Fixed in 7cbb608
